# Generated by Django 6.0.3 on 2026-04-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
    ]
